#pragma once

enum class STANDARD_POSE {
  STANDARD_POSE_NONE,
  STANDARD_POSE_OUTOFPLACE_DO_NOT_USE,
  STANDARD_POSE_IDLE,
  STANDARD_POSE_IDLE_BLIND,
  STANDARD_POSE_ALERT,
  STANDARD_POSE_ALERT_BLIND,
  STANDARD_POSE_ALERT_KNEELING,
  STANDARD_POSE_KNEELING_BLIND,
  STANDARD_POSE_FIRE_STOOD,
  STANDARD_POSE_FIRE_TURN,
  STANDARD_POSE_FIRE_STOOD_ATTRACT,
  STANDARD_POSE_FIRE_STOOD_GRENADE,
  STANDARD_POSE_FIRE_KNEELING,
  STANDARD_POSE_FIRE_KNEELING_TURN,
  STANDARD_POSE_FIRE_KNEELING_ATTRACT,
  STANDARD_POSE_FIRE_KNEELING_GRENADE,
  STANDARD_POSE_STATICGUN_FIRE,
  STANDARD_POSE_DUCK,
  STANDARD_POSE_HURT_STAND,
  STANDARD_POSE_HURT_KNEEL,
  STANDARD_POSE_DIE,
  STANDARD_POSE_DIE_FLYING,
  STANDARD_POSE_DROPSHIPFALL,
  STANDARD_POSE_ANIMLOOP,
};

enum AIMODE {
  AIMODE_STILL,
  AIMODE_MOVING,
  AIMODE_FIGHTING,
  AIMODE_IMMOBILE,
  AIMODE_DYING,
  AIMODE_RAGDOLL,
  AIMODE_DEAD,
  AIMODE_DESTROYED,
};

enum AIHUMAN {
  AIHUMAN_NOTYPE,
  AIHUMAN_PLAYER,
  AIHUMAN_TROOPER_GRUNT,
  AIHUMAN_TROOPER_MARAUDER,
  AIHUMAN_TROOPER_MEDIC,
  AIHUMAN_TROOPER_MECHANIC,
  AIHUMAN_TROOPER_SERGEANT,
  AIHUMAN_TROOPER_PSYOP,
  AIHUMAN_TROOPER_COMMS,
  AIHUMAN_PILOT,
  AIHUMAN_ACTOR,
  AIHUMAN_MULTIPLAYER__DO_NOT_USE,
  AIHUMAN_MAX_TYPES__DO_NOT_USE,
};

enum AIWEAPMODE {
  AIWEAPMODE_NOOWNER,
  AIWEAPMODE_PICKUP,
  AIWEAPMODE_INHAND,
  AIWEAPMODE_FIRE1,
  AIWEAPMODE_FIRE2,
  AIWEAPMODE_MODE12,
  AIWEAPMODE_INHAND2,
  AIWEAPMODE_MODE21,
  AIWEAPMODE_RELOAD,
  AIWEAPMODE_OFFSCREEN1,
  AIWEAPMODE_OFFSCREEN2,
  AIWEAPMODE_OFFSCREEN3,
  AIWEAPMODE_PUTONBACK,
  AIWEAPMODE_STOWED,
  AIWEAPMODE_TAKEOFFBACK,
  AIWEAPMODE_THROWAWAY,
  AIWEAPMODE_OBSTRUCTED_PUTONBACK,
  AIWEAPMODE_OBSTRUCTED_STOWED,
  AIWEAPMODE_OBSTRUCTED_TAKEOFFBACK,
};

enum BLEND {
  BLEND_ZERO,
  BLEND_ONE,
  BLEND_SRCCOLOR,
  BLEND_INVSRCCOLOR,
  BLEND_SRCALPHA,
  BLEND_INVSRCALPHA,
  BLEND_DESTALPHA,
  BLEND_INVDESTALPHA,
  BLEND_DESTCOLOR,
  BLEND_INVDESTCOLOR,
  BLEND_SRCALPHASAT,
  BLEND_BOTHSRCALPHA,
  BLEND_BOTHINVSRCALPHA,
  BLEND_BLENDFACTOR,
  BLEND_INVBLENDFACTOR,
};

enum AITYPEID {
  AITYPEID_NULL,
  AITYPEID_ENTITY,
  AITYPEID_CAMERA,
  AITYPEID_HUMAN,
  AITYPEID_PLAYER,
  AITYPEID_VEHICLE,
  AITYPEID_FLYINGVEHICLE,
  AITYPEID_BOMBER,
  AITYPEID_DROPSHIP,
  AITYPEID_DROPSHIPGRUNT,
  AITYPEID_DROPSHIPMARAUDER,
  AITYPEID_DROPSHIPCARGO,
  AITYPEID_BUG,
  AITYPEID_BUGWALKER,
  AITYPEID_BUGWARRIORBASE,
  AITYPEID_BUGWARRIOR,
  AITYPEID_BUGTIGER,
  AITYPEID_BUGTIGERSHARD,
  AITYPEID_BUGTIGERSPIT,
  AITYPEID_BUGROYAL,
  AITYPEID_BUGROYALX,
  AITYPEID_BUGRHINO,
  AITYPEID_BUGBABYTANKER,
  AITYPEID_BUGBABYPLASMA,
  AITYPEID_BUGBLASTER,
  AITYPEID_BUGCHARIOT,
  AITYPEID_BUGFLYER,
  AITYPEID_BUGHOPPER,
  AITYPEID_BUGHOPPERFIREFLY,
  AITYPEID_BUGHOPPERRIPPLER,
  AITYPEID_BUGTANKER,
  AITYPEID_BUGPLASMA,
  AITYPEID_BUGCLIFFMITE,
  AITYPEID_BUGSENTINEL,
  AITYPEID_BUGBRAIN,
  AITYPEID_FAKETARGET,
  AITYPEID_ENTITYGENERIC,
  AITYPEID_NONPHYSICALENTITY,
  AITYPEID_NUM,
};

enum AISQUADMODE {
  AISQUADMODE_STILL,
  AISQUADMODE_MOVING,
  AISQUADMODE_FOLLOWONPATH,
  AISQUADMODE_FOLLOWFREE,
  AISQUADMODE_MEMBERSFOLLOWPATHS,
  AISQUADMODE_GOTOHOTSPOTS_DONTUSE,
  AISQUADMODE_DISEMBARK,
};

enum AIHSM {
  AIHSM_NONE,
  AIHSM_PLAYANIM,
  AIHSM_PLAYANIMLOOP,
  AIHSM_THROWGRENADE,
  AIHSM_MANSTATICGUN,
  AIHSM_FLYING,
  AIHSM_DROPSHIP,
  AIHSM_SENTRY,
  AIHSM_TURN,
  AIHSM_LOOKPLAYER,
};

enum AIWT {
  AIWT_MORITIA_MK4,
  AIWT_MORITIA_MK2_SHOTGUN,
  AIWT_MORITIA_MK2_GRENADE,
  AIWT_HEAVY_SHOTGUN,
  AIWT_MORITIA_MK2_ZOOM,
  AIWT_MORITIA_MK2_CARBINE,
  AIWT_ROCKET_LAUNCHER,
  AIWT_RAILGUN,
  AIWT_MISSILE_LAUNCHER,
  AIWT_PSIOP_FAKE,
  AIWT_NUMCARRIEDWEAPS,
  AIWT_STATIC_SINGLE,
  AIWT_STATIC_DOUBLE,
  AIWT_STATIC_NUKE,
  AIWT_NONE,
  AIWT_NUM,
};

enum AIALERT {
  AIALERT_IDLE,
  AIALERT_ALERT,
  AIALERT_ATTACK,
  AIALERT_IGNORE,
};

enum SWITCHSTATE {
  SWITCHSTATE_OFF,
  SWITCHSTATE_SWITCHINGON,
  SWITCHSTATE_ON,
  SWITCHSTATE_SWITCHINGOFF,
  SWITCHSTATE_NUM,
};

enum PICKUP {
  PICKUP_HEALTH,
  PICKUP_POWERCELL,
  PICKUP_KEYCARD,
  PICKUP_MINELAYERS,
  PICKUP_EXPLOSIVES,
};

enum DOORSTATE {
  DOORSTATE_CLOSED,
  DOORSTATE_OPENING,
  DOORSTATE_OPENED,
  DOORSTATE_CLOSING,
  DOORSTATE_NUM,
};

enum AISQUADFORMATION {
  AISQUADFORMATION_ARROWHEAD,
  AISQUADFORMATION_DIAMOND,
  AISQUADFORMATION_SINGLEFILE,
  AISQUADFORMATION_LINE,
  AISQUADFORMATION_GRUNTDROPSHIP_ON,
  AISQUADFORMATION_GRUNTDROPSHIP_OFF,
  AISQUADFORMATION_NUMTYPES__DO_NOT_USE,
};

enum class SubObjectivePositionType {
  None,
  WorldPosition,
  WorldObject,
};

enum AIPBSM {
  AIPBSM_COWER,
  AIPBSM_FIREPROJECTILE,
  AIPBSM_TRACKPLAYER,
};

