#pragma once
#include <string>

enum TDSValueIndex {
  Misc_GenericParticleEffects_PoolSize = 0,
  Misc_TemporaryDecals_MaxOverlap = 1,
  Misc_TemporaryDecals_CullTime = 2,
  Misc_DecalDensity_DrawnContext = 3,
  Misc_DecalDensity_NonDrawnContext = 4,
  Misc_DecalRemoval_SizeFactor = 5,
  Misc_DecalRemoval_OverlapFactor = 6,
  Misc_Navigator_NumberAngleToCheck = 7,
  Misc_Navigator_LOW_LOD_Range = 8,
  Misc_Collisions_AutoRangeFactor0 = 9,
  Misc_Collisions_AutoRangeFactor1 = 10,
  Misc_Collisions_AutoRangeFactor2 = 11,
  Misc_BlastCameraShake_Time = 12,
  Misc_BlastCameraShake_Scale = 13,
  Misc_BlastCameraShake_MaxAngleX = 14,
  Misc_BlastCameraShake_MaxAngleY = 15,
  Misc_BlastCameraShake_MaxAngleZ = 16,
  Misc_MaxFlameSystems = 17,
  Misc_MaxSmokeSystems = 18,
  Warrior_SpottingTargetBias_Player = 19,
  Warrior_SpottingTargetBias_AIHuman = 20,
  Warrior_SpottingTargetBias_Vehicle = 21,
  Warrior_Defence_PercentageChance = 22,
  Warrior_Ragdoll_Density = 23,
  Warrior_Attack_PredictionSpeed = 24,
  Warrior_Attack_Strength = 25,
  Warrior_Strength_BulletNerveSoft = 26,
  Warrior_Strength_BulletNerveHard = 27,
  Warrior_Strength_BulletHeadSoft = 28,
  Warrior_Strength_BulletHeadHard = 29,
  Warrior_Strength_BulletLegsSoft = 30,
  Warrior_Strength_BulletLegsHard = 31,
  Warrior_Strength_Slash = 32,
  Warrior_Strength_Punch = 33,
  Warrior_Strength_Blast = 34,
  Warrior_Strength_Heat = 35,
  Warrior_Strength_Corrosive = 36,
  Warrior_Strength_Electricity = 37,
  Warrior_Strength_PsiOps = 38,
  Warrior_Strength_Sonic = 39,
  Warrior_Strength_CosmeticShields = 40,
  Warrior_Strength_CosmeticShields_0 = 41,
  Warrior_Health_CosmeticShields = 42,
  Warrior_Damage_NonPlayerFactor = 43,
  Warrior_Fire_ResistanceThreshold = 44,
  Warrior_Fire_OnFireDamageRate = 45,
  Warrior_Idle_RangeMin = 46,
  Warrior_Idle_RangeMax = 47,
  Warrior_Idle_Chance = 48,
  Warrior_Idle_Cone = 49,
  Warrior_Alert_RangeMin = 50,
  Warrior_Alert_RangeMax = 51,
  Warrior_Alert_Chance = 52,
  Warrior_Alert_Cone = 53,
  Warrior_Spotting_TorchSightModifier = 54,
  Warrior_Navigator_CapsuleRadius = 55,
  Warrior_Navigator_CapsuleOffsetX = 56,
  Warrior_Navigator_CapsuleOffsetY = 57,
  Warrior_Navigator_CapsuleOffsetZ = 58,
  Warrior_Navigator_CapsuleRadiusIgnore = 59,
  Warrior_Navigator_BaseSizeX = 60,
  Warrior_Navigator_BaseSizeY = 61,
  Warrior_Navigator_BaseSizeZ = 62,
  Warrior_Navigator_MaxGradient = 63,
  Warrior_NavigatorSpeedData0_StepLength = 64,
  Warrior_NavigatorSpeedData0_StepTime = 65,
  Warrior_NavigatorSpeedData0_MaxTurn = 66,
  Warrior_NavigatorSpeedData1_StepLength = 67,
  Warrior_NavigatorSpeedData1_StepTime = 68,
  Warrior_NavigatorSpeedData1_MaxTurn = 69,
  Warrior_NavigatorSpeedData2_StepLength = 70,
  Warrior_NavigatorSpeedData2_StepTime = 71,
  Warrior_NavigatorSpeedData2_MaxTurn = 72,
  Warrior_Death_DeltaHealthForGib = 73,
  Warrior_Death_BodyMovementFactor = 74,
  Warrior_FootImpact_DustRateModifier = 75,
  Tiger_SpottingTargetBias_Player = 76,
  Tiger_SpottingTargetBias_AIHuman = 77,
  Tiger_SpottingTargetBias_Vehicle = 78,
  Tiger_Defence_PercentageChance = 79,
  Tiger_Attack_PredictionSpeed = 80,
  Tiger_Attack_Strength = 81,
  Tiger_Strength_BulletNerve = 82,
  Tiger_Strength_BulletHead = 83,
  Tiger_Strength_BulletLegs = 84,
  Tiger_Strength_Blast = 85,
  Tiger_Strength_Heat = 86,
  Tiger_Strength_Sonic = 87,
  Tiger_Strength_CosmeticShieldsPierce = 88,
  Tiger_Health_CosmeticShields = 89,
  Tiger_Damage_NonPlayerFactor = 90,
  Tiger_Fire_ResistanceThreshold = 91,
  Tiger_Fire_OnFireDamageRate = 92,
  Tiger_Idle_RangeMin = 93,
  Tiger_Idle_RangeMax = 94,
  Tiger_Idle_Chance = 95,
  Tiger_Idle_Cone = 96,
  Tiger_Alert_RangeMin = 97,
  Tiger_Alert_RangeMax = 98,
  Tiger_Alert_RangeChance = 99,
  Tiger_Alert_Cone = 100,
  Tiger_Spotting_TorchSightModifier = 101,
  Tiger_Strategy_EvasionChance = 102,
  Tiger_Strategy_EvasionDist = 103,
  Tiger_Navigator_CapsuleRadius = 104,
  Tiger_Navigator_CapsuleOffsetX = 105,
  Tiger_Navigator_CapsuleOffsetY = 106,
  Tiger_Navigator_CapsuleOffsetZ = 107,
  Tiger_Navigator_CapsuleRadiusIgnore = 108,
  Tiger_Navigator_BaseSizeX = 109,
  Tiger_Navigator_BaseSizeY = 110,
  Tiger_Navigator_BaseSizeZ = 111,
  Tiger_Navigator_MaxGradient = 112,
  Tiger_Navigator_SpeedData0StepLength = 113,
  Tiger_Navigator_SpeedData0StepTime = 114,
  Tiger_Navigator_SpeedData0MaxTurn = 115,
  Tiger_Navigator_SpeedData1StepLength = 116,
  Tiger_Navigator_SpeedData1StepTime = 117,
  Tiger_Navigator_SpeedData1MaxTurn = 118,
  Tiger_Navigator_SpeedData2StepLength = 119,
  Tiger_Navigator_SpeedData2StepTime = 120,
  Tiger_Navigator_SpeedData2MaxTurn = 121,
  Tiger_Death_DeltaHealthForGib = 122,
  Tiger_Death_BodyMovementFactor = 123,
  TigerShard_SpottingTargetBias_Player = 124,
  TigerShard_SpottingTargetBias_AIHuman = 125,
  TigerShard_SpottingTargetBias_Vehicle = 126,
  TigerShard_Attack_PredictionSpeed = 127,
  TigerShard_Defence_PercentageChance = 128,
  TigerShard_Attack_Strength = 129,
  TigerShard_Strength_BulletNerve = 130,
  TigerShard_Strength_BulletHead = 131,
  TigerShard_Strength_BulletLegs = 132,
  TigerShard_Strength_Blast = 133,
  TigerShard_Strength_Heat = 134,
  TigerShard_Strength_Sonic = 135,
  TigerShard_Damage_NonPlayerFactor = 136,
  TigerShard_Fire_ResistanceThreshold = 137,
  TigerShard_Fire_OnFireDamageRate = 138,
  TigerShard_Idle_RangeMin = 139,
  TigerShard_Idle_RangeMax = 140,
  TigerShard_Idle_Chance = 141,
  TigerShard_Idle_Cone = 142,
  TigerShard_Alert_RangeMin = 143,
  TigerShard_Alert_RangeMax = 144,
  TigerShard_Alert_RangeChance = 145,
  TigerShard_Alert_Cone = 146,
  TigerShard_Spotting_TorchSightModifier = 147,
  TigerShard_Weapon_MeleeRange = 148,
  TigerShard_Weapon_InnerRange = 149,
  TigerShard_Weapon_OuterRange = 150,
  TigerShard_Weapon_FireAngle = 151,
  TigerShard_Weapon_ConeSpreadX = 152,
  TigerShard_Weapon_ConeSpreadY = 153,
  TigerShard_Weapon_ConeSpreadZ = 154,
  TigerShard_Weapon_ConeAngle = 155,
  TigerShard_Weapon_ConeNumShards = 156,
  TigerShard_Weapon_Damage = 157,
  TigerShard_Strategy_IdealDist = 158,
  TigerShard_Strategy_EvasionDistance = 159,
  TigerShard_Strategy_EvasionChance = 160,
  TigerShard_Strategy_BerserkHealth = 161,
  TigerShard_Strategy_MeleeAttackDist = 162,
  TigerShard_Strategy_ShortFireDist = 163,
  TigerShard_Strategy_ShortFireChance = 164,
  TigerShard_Navigator_CapsuleRadius = 165,
  TigerShard_Navigator_CapsuleOffsetX = 166,
  TigerShard_Navigator_CapsuleOffsetY = 167,
  TigerShard_Navigator_CapsuleOffsetZ = 168,
  TigerShard_Navigator_CapsuleRadiusIgnore = 169,
  TigerShard_Navigator_BaseSizeX = 170,
  TigerShard_Navigator_BaseSizeY = 171,
  TigerShard_Navigator_BaseSizeZ = 172,
  TigerShard_Navigator_MaxGradient = 173,
  TigerShard_Navigator_SpeedData0StepLength = 174,
  TigerShard_Navigator_SpeedData0StepTime = 175,
  TigerShard_Navigator_SpeedData0MaxTurn = 176,
  TigerShard_Navigator_SpeedData1StepLength = 177,
  TigerShard_Navigator_SpeedData1StepTime = 178,
  TigerShard_Navigator_SpeedData1MaxTurn = 179,
  TigerShard_Navigator_SpeedData2StepLength = 180,
  TigerShard_Navigator_SpeedData2StepTime = 181,
  TigerShard_Navigator_SpeedData2MaxTurn = 182,
  TigerShard_Accuracy_MinimumVariance = 183,
  TigerShard_Accuracy_MaximumVariance = 184,
  TigerShard_Accuracy_NumberOfIntervals = 185,
  TigerShard_Accuracy_FirePredictionTime = 186,
  TigerShard_Bolt_Speed = 187,
  TigerShard_Bolt_Life = 188,
  TigerSpit_SpottingTargetBias_Player = 189,
  TigerSpit_SpottingTargetBias_AIHuman = 190,
  TigerSpit_SpottingTargetBias_Vehicle = 191,
  TigerSpit_Defence_PercentageChance = 192,
  TigerSpit_Attack_PredictionSpeed = 193,
  TigerSpit_Attack_Strength = 194,
  TigerSpit_Strength_BulletNerve = 195,
  TigerSpit_Strength_BulletHead = 196,
  TigerSpit_Strength_BulletLegs = 197,
  TigerSpit_Strength_Blast = 198,
  TigerSpit_Strength_Heat = 199,
  TigerSpit_Strength_Sonic = 200,
  TigerSpit_Damage_NonPlayerFactor = 201,
  TigerSpit_Fire_ResistanceThreshold = 202,
  TigerSpit_Fire_OnFireDamageRate = 203,
  TigerSpit_Idle_RangeMin = 204,
  TigerSpit_Idle_RangeMax = 205,
  TigerSpit_Idle_Chance = 206,
  TigerSpit_Idle_Cone = 207,
  TigerSpit_Alert_RangeMin = 208,
  TigerSpit_Alert_RangeMax = 209,
  TigerSpit_Alert_RangeChance = 210,
  TigerSpit_Alert_Cone = 211,
  TigerSpit_Spotting_TorchSightModifier = 212,
  TigerSpit_Weapon_MeleeRange = 213,
  TigerSpit_Weapon_InnerRange = 214,
  TigerSpit_Weapon_OuterRange = 215,
  TigerSpit_Weapon_SpitAngle = 216,
  TigerSpit_Strategy_IdealDist = 217,
  TigerSpit_Strategy_EvasionDistance = 218,
  TigerSpit_Strategy_EvasionChance = 219,
  TigerSpit_Strategy_BerserkHealth = 220,
  TigerSpit_Strategy_MeleeAttackDist = 221,
  TigerSpit_Strategy_ShotSpitDist = 222,
  TigerSpit_Strategy_ShotSpitChance = 223,
  TigerSpit_Navigator_CapsuleRadius = 224,
  TigerSpit_Navigator_CapsuleOffsetX = 225,
  TigerSpit_Navigator_CapsuleOffsetY = 226,
  TigerSpit_Navigator_CapsuleOffsetZ = 227,
  TigerSpit_Navigator_CapsuleRadiusIgnore = 228,
  TigerSpit_Navigator_BaseSizeX = 229,
  TigerSpit_Navigator_BaseSizeY = 230,
  TigerSpit_Navigator_BaseSizeZ = 231,
  TigerSpit_Navigator_MaxGradient = 232,
  TigerSpit_Navigator_SpeedData0StepLength = 233,
  TigerSpit_Navigator_SpeedData0StepTime = 234,
  TigerSpit_Navigator_SpeedData0MaxTurn = 235,
  TigerSpit_Navigator_SpeedData1StepLength = 236,
  TigerSpit_Navigator_SpeedData1StepTime = 237,
  TigerSpit_Navigator_SpeedData1MaxTurn = 238,
  TigerSpit_Navigator_SpeedData2StepLength = 239,
  TigerSpit_Navigator_SpeedData2StepTime = 240,
  TigerSpit_Navigator_SpeedData2MaxTurn = 241,
  TigerSpit_Accuracy_MinimumVariance = 242,
  TigerSpit_Accuracy_MaximumVariance = 243,
  TigerSpit_Accuracy_NumberOfIntervals = 244,
  TigerSpit_Accuracy_SpitPredictionTime = 245,
  TigerSpit_Bolt_BlastForce = 246,
  TigerSpit_Bolt_BlastHotspot = 247,
  TigerSpit_Bolt_BlastFalloff = 248,
  TigerSpit_Bolt_Speed = 249,
  WarriorRoyal_SpottingTargetBias_Player = 250,
  WarriorRoyal_SpottingTargetBias_AIHuman = 251,
  WarriorRoyal_SpottingTargetBias_Vehicle = 252,
  WarriorRoyal_Defence_PercentageChance = 253,
  WarriorRoyal_Ragdoll_Density = 254,
  WarriorRoyal_Attack_PredictionSpeed = 255,
  WarriorRoyal_Attack_Strength = 256,
  WarriorRoyal_LegPunches_MinLegVelocity = 257,
  WarriorRoyal_LegPunches_ColSphereRadius = 258,
  WarriorRoyal_LegPunches_ImpactPunchForce = 259,
  WarriorRoyal_FootImpact_PunchMultiplier = 260,
  WarriorRoyal_Strength_EyeShieldPierceSoft = 261,
  WarriorRoyal_Strength_EyeShieldPierceHard = 262,
  WarriorRoyal_Strength_EyePierceSoft = 263,
  WarriorRoyal_Strength_EyePierceHard = 264,
  WarriorRoyal_Strength_Punch = 266,
  WarriorRoyal_Strength_Blast = 267,
  WarriorRoyal_Strength_Heat = 268,
  WarriorRoyal_Strength_Corrosive = 269,
  WarriorRoyal_Strength_Electricity = 270,
  WarriorRoyal_Strength_PsiOps = 271,
  WarriorRoyal_DamageThreshold_Threshold = 272,
  WarriorRoyal_Health_EyeSheildLeft = 273,
  WarriorRoyal_Health_EyeSheildRight = 274,
  WarriorRoyal_Health_EyeLeft = 275,
  WarriorRoyal_Health_EyeRight = 276,
  WarriorRoyal_Health_CosmeticShields = 277,
  WarriorRoyal_Health_MandibleShields = 278,
  WarriorRoyal_Damage_NonPlayerFactor = 279,
  WarriorRoyal_Fire_ResistanceThreshold = 280,
  WarriorRoyal_Strategy_OutOfDistanceAttackRoarChance = 281,
  WarriorRoyal_Strategy_OutOfDistanceAttackRoarRange = 282,
  WarriorRoyal_Strategy_RandomRoarChance = 283,
  WarriorRoyal_Strategy_RandomRoarMinDistance = 284,
  WarriorRoyal_Strategy_FacingTargetAngle = 285,
  WarriorRoyal_SpottingIdle_RangeMin = 286,
  WarriorRoyal_SpottingIdle_RangeMax = 287,
  WarriorRoyal_SpottingIdle_Chance = 288,
  WarriorRoyal_SpottingIdle_Cone = 289,
  WarriorRoyal_SpottingAlert_RangeMin = 290,
  WarriorRoyal_SpottingAlert_RangeMax = 291,
  WarriorRoyal_SpottingAlert_RangeChance = 292,
  WarriorRoyal_SpottingAlert_Cone = 293,
  WarriorRoyal_Spotting_TorchSightModifier = 294,
  WarriorRoyal_Misc_EyeRadius = 295,
  WarriorRoyal_Navigator_CapsuleRadius = 296,
  WarriorRoyal_Navigator_CapsuleOffsetX = 297,
  WarriorRoyal_Navigator_CapsuleOffsetY = 298,
  WarriorRoyal_Navigator_CapsuleOffsetZ = 299,
  WarriorRoyal_Navigator_CapsuleRadiusIgnore = 300,
  WarriorRoyal_Navigator_BaseSizeX = 301,
  WarriorRoyal_Navigator_BaseSizeY = 302,
  WarriorRoyal_Navigator_BaseSizeZ = 303,
  WarriorRoyal_Navigator_MaxGradient = 304,
  WarriorRoyal_Navigator_SpeedData0StepLength = 305,
  WarriorRoyal_Navigator_SpeedData0StepTime = 306,
  WarriorRoyal_Navigator_SpeedData0MaxTurn = 307,
  WarriorRoyal_Navigator_SpeedData1StepLength = 308,
  WarriorRoyal_Navigator_SpeedData1StepTime = 309,
  WarriorRoyal_Navigator_SpeedData1MaxTurn = 310,
  WarriorRoyal_Navigator_SpeedData2StepLength = 311,
  WarriorRoyal_Navigator_SpeedData2StepTime = 312,
  WarriorRoyal_Navigator_SpeedData2MaxTurn = 313,
  WarriorRoyalX_SpottingTargetBias_Player = 314,
  WarriorRoyalX_SpottingTargetBias_AIHuman = 315,
  WarriorRoyalX_SpottingTargetBias_Vehicle = 316,
  WarriorRoyalX_Defence_PercentageChance = 317,
  WarriorRoyalX_Ragdoll_Density = 318,
  WarriorRoyalX_Attack_PredictionSpeed = 319,
  WarriorRoyalX_Attack_Strength = 320,
  WarriorRoyalX_LegPunches_MinLegVelocity = 321,
  WarriorRoyalX_LegPunches_ColSphereRadius = 322,
  WarriorRoyalX_LegPunches_ImpactPunchForce = 323,
  WarriorRoyalX_FootImpact_PunchMultiplier = 324,
  WarriorRoyalX_Strength_EyeShieldPierceSoft = 325,
  WarriorRoyalX_Strength_EyeShieldPierceHard = 326,
  WarriorRoyalX_Strength_EyePierceSoft = 327,
  WarriorRoyalX_Strength_EyepierceHard = 328,
  WarriorRoyalX_Strength_Punch = 330,
  WarriorRoyalX_Strength_Blast = 331,
  WarriorRoyalX_Strength_Heat = 332,
  WarriorRoyalX_Strength_Corrosive = 333,
  WarriorRoyalX_Strength_Electricity = 334,
  WarriorRoyalX_Strength_PsiOps = 335,
  WarriorRoyalX_Strength_AnnoyedRearUpSoft = 336,
  WarriorRoyalX_Strength_AnnoyedRearUpHard = 337,
  WarriorRoyalX_DamageThreshold_Threshold = 338,
  WarriorRoyalX_Health_EyeSheildLeft = 339,
  WarriorRoyalX_Health_EyeSheildRight = 340,
  WarriorRoyalX_Health_EyeLeft = 341,
  WarriorRoyalX_Health_EyeRight = 342,
  WarriorRoyalX_Health_CosmeticShields = 343,
  WarriorRoyalX_Health_MandibleShields = 344,
  WarriorRoyalX_Health_RearUpDamageTrigger = 345,
  WarriorRoyalX_Strategy_SonicRadialRoarChance = 346,
  WarriorRoyalX_Strategy_SonicRadialRoarDistance = 347,
  WarriorRoyalX_Strategy_SonicRoarChance = 348,
  WarriorRoyalX_Strategy_SonicRoarDistance = 349,
  WarriorRoyalX_Strategy_JetFireChance = 350,
  WarriorRoyalX_Strategy_BlastDelayTime = 351,
  WarriorRoyalX_Damage_NonPlayerFactor = 352,
  WarriorRoyalX_Damage_SonicBlastIntensity = 353,
  WarriorRoyalX_Fire_ResistanceThreshold = 354,
  WarriorRoyalX_SpottingIdle_RangeMin = 355,
  WarriorRoyalX_SpottingIdle_RangeMax = 356,
  WarriorRoyalX_SpottingIdle_Chance = 357,
  WarriorRoyalX_SpottingIdle_Cone = 358,
  WarriorRoyalX_SpottingAlert_RangeMin = 359,
  WarriorRoyalX_SpottingAlert_RangeMax = 360,
  WarriorRoyalX_SpottingAlert_RangeChance = 361,
  WarriorRoyalX_SpottingAlert_Cone = 362,
  WarriorRoyalX_Spotting_TorchSightModifier = 363,
  WarriorRoyalX_Misc_EyeRadius = 364,
  WarriorRoyalX_Navigator_CapsuleRadius = 365,
  WarriorRoyalX_Navigator_CapsuleOffsetX = 366,
  WarriorRoyalX_Navigator_CapsuleOffsetY = 367,
  WarriorRoyalX_Navigator_CapsuleOffsetZ = 368,
  WarriorRoyalX_Navigator_CapsuleRadiusIgnore = 369,
  WarriorRoyalX_Navigator_BaseSizeX = 370,
  WarriorRoyalX_Navigator_BaseSizeY = 371,
  WarriorRoyalX_Navigator_BaseSizeZ = 372,
  WarriorRoyalX_Navigator_MaxGradient = 373,
  WarriorRoyalX_Navigator_SpeedData0StepLength = 374,
  WarriorRoyalX_Navigator_SpeedData0StepTime = 375,
  WarriorRoyalX_Navigator_SpeedData0MaxTurn = 376,
  WarriorRoyalX_Navigator_SpeedData1StepLength = 377,
  WarriorRoyalX_Navigator_SpeedData1StepTime = 378,
  WarriorRoyalX_Navigator_SpeedData1MaxTurn = 379,
  WarriorRoyalX_Navigator_SpeedData2StepLength = 380,
  WarriorRoyalX_Navigator_SpeedData2StepTime = 381,
  WarriorRoyalX_Navigator_SpeedData2MaxTurn = 382,
  Cliffmite_SpottingTargetBias_Player = 383,
  Cliffmite_SpottingTargetBias_AIHuman = 384,
  Cliffmite_SpottingTargetBias_Vehicle = 385,
  Cliffmite_Spotting_IdleRangeMin = 386,
  Cliffmite_Spotting_IdleRangeMax = 387,
  Cliffmite_Spotting_IdleChance = 388,
  Cliffmite_Spotting_IdleCone = 389,
  Cliffmite_Spotting_AlertRangeMin = 390,
  Cliffmite_Spotting_AlertRangeMax = 391,
  Cliffmite_Spotting_AlertChance = 392,
  Cliffmite_Spotting_AlertCone = 393,
  Cliffmite_Spotting_TorchSightModifier = 394,
  Cliffmite_DamageStrength_PierceSoft = 395,
  Cliffmite_DamageStrength_PierceHard = 396,
  Cliffmite_DamageStrength_Slash = 397,
  Cliffmite_DamageStrength_Punch = 398,
  Cliffmite_DamageStrength_Blast = 399,
  Cliffmite_DamageStrength_Heat = 400,
  Cliffmite_DamageStrength_Corrosive = 401,
  Cliffmite_DamageStrength_Electricity = 402,
  Cliffmite_DamageStrength_PsiOps = 403,
  Cliffmite_Attack_MaxFiringArc = 404,
  Cliffmite_Attack_NearRange = 405,
  Cliffmite_Attack_FarRange = 406,
  Cliffmite_Attack_NearChance = 407,
  Cliffmite_Attack_FarChance = 408,
  Cliffmite_Damage_NonPlayerFactor = 409,
  Cliffmite_Missile_Speed = 410,
  Cliffmite_Missile_Life = 411,
  Cliffmite_Missile_Damage = 412,
  Cliffmite_Missile_MinDamageFactor = 413,
  Cliffmite_Accuracy_MinimumVariance = 414,
  Cliffmite_Accuracy_MaximumVariance = 415,
  Cliffmite_Accuracy_NumberOfIntervals = 416,
  Cliffmite_Accuracy_FirePredictionTime = 417,
  Sentinel_SpottingTargetBias_Player = 418,
  Sentinel_SpottingTargetBias_AIHuman = 419,
  Sentinel_SpottingTargetBias_Vehicle = 420,
  Sentinel_SpottingIdle_RangeMin = 421,
  Sentinel_SpottingIdle_RangeMax = 422,
  Sentinel_SpottingIdle_Chance = 423,
  Sentinel_SpottingIdle_Cone = 424,
  Sentinel_SpottingAlert_RangeMin = 425,
  Sentinel_SpottingAlert_RangeMax = 426,
  Sentinel_SpottingAlert_Chance = 427,
  Sentinel_SpottingAlert_Cone = 428,
  Sentinel_Spotting_TorchSightModifier = 429,
  Sentinel_Attack_ZapDistance = 430,
  Sentinel_Attack_FlashFalloffMin = 431,
  Sentinel_Attack_FlashCutoffMax = 432,
  Sentinel_Attack_FlashIntensity = 433,
  Sentinel_Strength_BulletSoft = 434,
  Sentinel_Strength_BulletHard = 435,
  Sentinel_Strength_Slash = 436,
  Sentinel_Strength_Punch = 437,
  Sentinel_Strength_Blast = 438,
  Sentinel_Strength_Heat = 439,
  Sentinel_Strength_Corrosive = 440,
  Sentinel_Strength_Electricity = 441,
  Sentinel_Strength_PsiOps = 442,
  Sentinel_Damage_NonPlayerFactor = 443,
  Sentinel_Fire_ResistanceThreshold = 444,
  Charriot_SpottingTargetBias_Player = 445,
  Charriot_SpottingTargetBias_AIHuman = 446,
  Charriot_SpottingTargetBias_Vehicle = 447,
  Charriot_SpottingIdle_RangeMax = 448,
  Charriot_SpottingIdle_RangeMin = 449,
  Charriot_SpottingIdle_Chance = 450,
  Charriot_SpottingIdle_Cone = 451,
  Charriot_SpottingAlert_RangeMax = 452,
  Charriot_SpottingAlert_RangeMin = 453,
  Charriot_SpottingAlert_Chance = 454,
  Charriot_SpottingAlert_Cone = 455,
  Charriot_Spotting_TorchSightModifier = 456,
  Charriot_DamageStrengthHead_PierceSoft = 457,
  Charriot_DamageStrengthHead_PierceHard = 458,
  Charriot_DamageStrengthHead_Slash = 459,
  Charriot_DamageStrengthHead_Punch = 460,
  Charriot_DamageStrengthHead_Blast = 461,
  Charriot_DamageStrengthHead_Heat = 462,
  Charriot_DamageStrengthHead_Corrosive = 463,
  Charriot_DamageStrengthHead_Electricity = 464,
  Charriot_DamageStrengthHead_PsiOps = 465,
  Charriot_Damage_NonPlayerFactor = 466,
  Charriot_Fire_ResistanceThreshold = 467,
  Charriot_Strategy_ScurryDistance = 468,
  Charriot_Strategy_MillingMoveChance = 469,
  Charriot_Strategy_MillingRadius = 470,
  Charriot_Navigator_CapsuleRadius = 471,
  Charriot_Navigator_CapsuleOffsetX = 472,
  Charriot_Navigator_CapsuleOffsetY = 473,
  Charriot_Navigator_CapsuleOffsetZ = 474,
  Charriot_Navigator_CapsuleRadiusIgnore = 475,
  Charriot_Navigator_BaseSizeX = 476,
  Charriot_Navigator_BaseSizeY = 477,
  Charriot_Navigator_BaseSizeZ = 478,
  Charriot_Navigator_SpeedData0StepLength = 479,
  Charriot_Navigator_SpeedData0StepTime = 480,
  Charriot_Navigator_SpeedData0MaxTurn = 481,
  Charriot_Navigator_SpeedData1StepLength = 482,
  Charriot_Navigator_SpeedData1StepTime = 483,
  Charriot_Navigator_SpeedData1MaxTurn = 484,
  Charriot_Navigator_MaxGradient = 485,
  Rhino_SpottingTargetBias_Player = 486,
  Rhino_SpottingTargetBias_AIHuman = 487,
  Rhino_SpottingTargetBias_Vehicle = 488,
  Rhino_SpottingIdle_RangeMax = 489,
  Rhino_SpottingIdle_RangeMin = 490,
  Rhino_SpottingIdle_Chance = 491,
  Rhino_SpottingIdle_Cone = 492,
  Rhino_SpottingAlert_RangeMax = 493,
  Rhino_SpottingAlert_RangeMin = 494,
  Rhino_SpottingAlert_Chance = 495,
  Rhino_SpottingAlert_Cone = 496,
  Rhino_Spotting_TorchSightModifier = 497,
  Rhino_DamageStrengthHead_PierceSoft = 498,
  Rhino_DamageStrengthHead_PierceHard = 499,
  Rhino_DamageStrengthHead_Slash = 500,
  Rhino_DamageStrengthHead_Punch = 501,
  Rhino_DamageStrengthHead_Blast = 502,
  Rhino_DamageStrengthHead_Heat = 503,
  Rhino_DamageStrengthHead_Corrosive = 504,
  Rhino_DamageStrengthHead_Electricity = 505,
  Rhino_DamageStrengthHead_PsiOps = 506,
  Rhino_DamageStrengthThreshold_Threshold = 507,
  Rhino_DamageStrengthRear_PierceSoft = 508,
  Rhino_DamageStrengthRear_PierceHard = 509,
  Rhino_DamageStrengthRear_Slash = 510,
  Rhino_DamageStrengthRear_Punch = 511,
  Rhino_DamageStrengthRear_Blast = 512,
  Rhino_DamageStrengthRear_Heat = 513,
  Rhino_DamageStrengthRear_Corrosive = 514,
  Rhino_DamageStrengthRear_Electricity = 515,
  Rhino_DamageStrengthRear_PsiOps = 516,
  Rhino_Damage_NonPlayerFactor = 517,
  Rhino_Attack_ChargeForceFront = 518,
  Rhino_Attack_ChargeForceTop = 519,
  Rhino_Attack_AttackStill = 520,
  Rhino_FootImpact_PunchMultiplierFLeg = 521,
  Rhino_FootImpact_PunchMultiplierRLeg = 522,
  Rhino_FootImpact_DustRateModifier = 523,
  Rhino_Strategy_ChargePastDistance = 524,
  Rhino_Strategy_ChargeHeadDipDistance = 525,
  Rhino_Strategy_SlideDistance = 526,
  Rhino_Strategy_SlideHoldTime = 527,
  Rhino_Navigator_CapsuleRadius = 528,
  Rhino_Navigator_CapsuleOffsetX = 529,
  Rhino_Navigator_CapsuleOffsetY = 530,
  Rhino_Navigator_CapsuleOffsetZ = 531,
  Rhino_Navigator_CapsuleRadiusIgnore = 532,
  Rhino_Navigator_BaseSizeX = 533,
  Rhino_Navigator_BaseSizeY = 534,
  Rhino_Navigator_BaseSizeZ = 535,
  Rhino_Navigator_MaxGradient = 536,
  Rhino_Navigator_SpeedData0StepLength = 537,
  Rhino_Navigator_SpeedData0StepTime = 538,
  Rhino_Navigator_SpeedData0MaxTurn = 539,
  Rhino_Navigator_SpeedData1StepLength = 540,
  Rhino_Navigator_SpeedData1StepTime = 541,
  Rhino_Navigator_SpeedData1MaxTurn = 542,
  Rhino_Navigator_SpeedData2StepLength = 543,
  Rhino_Navigator_SpeedData2StepTime = 544,
  Rhino_Navigator_SpeedData2MaxTurn = 545,
  Tanker_SpottingTargetBias_Player = 546,
  Tanker_SpottingTargetBias_AIHuman = 547,
  Tanker_SpottingTargetBias_Vehicle = 548,
  Tanker_Bullet_Head = 549,
  Tanker_Bullet_Rest = 550,
  Tanker_Blast_Head = 551,
  Tanker_Blast_Rest = 552,
  Tanker_Spotting_RangeMin = 553,
  Tanker_Spotting_RangeMax = 554,
  Tanker_Spotting_Cone = 555,
  Tanker_Spotting_Chance = 556,
  Tanker_Stomp_Strength = 557,
  Tanker_Stomp_Hotspot = 558,
  Tanker_Stomp_Falloff = 559,
  Tanker_Fire_DamageDelay = 560,
  Tanker_Fire_Strength = 561,
  Tanker_Fire_Hotspot = 562,
  Tanker_Fire_Falloff = 563,
  Tanker_Health_ValRetract = 564,
  Tanker_Damage_NonPlayerFactor = 565,
  Tanker_Spotting_TorchSightModifier = 566,
  Tanker_FootImpact_DustRateModifier = 567,
  TankerBaby_SpottingTargetBias_Player = 568,
  TankerBaby_SpottingTargetBias_AIHuman = 569,
  TankerBaby_SpottingTargetBias_Vehicle = 570,
  TankerBaby_SpottingIdle_RangeMax = 571,
  TankerBaby_SpottingIdle_RangeMin = 572,
  TankerBaby_SpottingIdle_Chance = 573,
  TankerBaby_SpottingIdle_Cone = 574,
  TankerBaby_SpottingAlert_RangeMax = 575,
  TankerBaby_SpottingAlert_RangeMin = 576,
  TankerBaby_SpottingAlert_Chance = 577,
  TankerBaby_SpottingAlert_Cone = 578,
  TankerBaby_Spotting_TorchSightModifier = 579,
  TankerBaby_Attack_FireBurstRange = 580,
  TankerBaby_Attack_BlastForce = 581,
  TankerBaby_Attack_BlastHotSpot = 582,
  TankerBaby_Attack_BlastFalloff = 583,
  TankerBaby_Attack_BoltSpeed = 584,
  TankerBaby_Attack_ForceBarge = 585,
  TankerBaby_FootImpact_PunchMultiplierFLeg = 586,
  TankerBaby_FootImpact_PunchMultiplierRLeg = 587,
  TankerBaby_FootImpact_DustRateModifier = 588,
  TankerBaby_DamageStrengthHead_PierceHard = 589,
  TankerBaby_DamageStrengthHead_PierceSoft = 590,
  TankerBaby_DamageStrengthHead_Blast = 591,
  TankerBaby_DamageStrengthHead_Slash = 592,
  TankerBaby_DamageStrengthHead_Punch = 593,
  TankerBaby_DamageStrengthHead_Heat = 594,
  TankerBaby_DamageStrengthHead_Corrosive = 595,
  TankerBaby_DamageStrengthHead_Electricity = 596,
  TankerBaby_DamageStrengthHead_PsiOps = 597,
  TankerBaby_DamageStrength_Threshold = 598,
  TankerBaby_Damage_NonPlayerFactor = 599,
  TankerBaby_NetworkStrategy_MinTimeBeforeMove = 600,
  TankerBaby_NetworkStrategy_MoveWaypointChance = 601,
  TankerBaby_NetworkStrategy_WPDeltaHealth = 602,
  TankerBaby_NetworkStrategy_DeltaHealthMoveChance = 603,
  TankerBaby_Accuracy_MinimumVariance = 604,
  TankerBaby_Accuracy_MaximumVariance = 605,
  TankerBaby_Accuracy_NumIntervals = 606,
  TankerBaby_Accuracy_FirePredictionTime = 607,
  TankerBaby_Navigator_CapsuleRadius = 608,
  TankerBaby_Navigator_CapsuleOffsetX = 609,
  TankerBaby_Navigator_CapsuleOffsetY = 610,
  TankerBaby_Navigator_CapsuleOffsetZ = 611,
  TankerBaby_Navigator_CapsuleRadiusIgnore = 612,
  TankerBaby_Navigator_BaseSizeX = 613,
  TankerBaby_Navigator_BaseSizeY = 614,
  TankerBaby_Navigator_BaseSizeZ = 615,
  TankerBaby_Navigator_MaxGradient = 616,
  TankerBaby_Navigator_SpeedData0StepLength = 617,
  TankerBaby_Navigator_SpeedData0StepTime = 618,
  TankerBaby_Navigator_SpeedData0MaxTurn = 619,
  TankerBaby_Navigator_SpeedData1StepLength = 620,
  TankerBaby_Navigator_SpeedData1StepTime = 621,
  TankerBaby_Navigator_SpeedData1MaxTurn = 622,
  BabyPlasma_SpottingTargetBias_Player = 623,
  BabyPlasma_SpottingTargetBias_AIHuman = 624,
  BabyPlasma_SpottingTargetBias_Vehicle = 625,
  BabyPlasma_SpottingIdle_RangeMax = 626,
  BabyPlasma_SpottingIdle_RangeMin = 627,
  BabyPlasma_SpottingIdle_Chance = 628,
  BabyPlasma_SpottingIdle_Cone = 629,
  BabyPlasma_SpottingAlert_RangeMax = 630,
  BabyPlasma_SpottingAlert_RangeMin = 631,
  BabyPlasma_SpottingAlert_Chance = 632,
  BabyPlasma_SpottingAlert_Cone = 633,
  BabyPlasma_Spotting_TorchSightModifier = 634,
  BabyPlasma_DamageStrengthHead_PierceSoft = 635,
  BabyPlasma_DamageStrengthHead_PierceHard = 636,
  BabyPlasma_DamageStrengthHead_Slash = 637,
  BabyPlasma_DamageStrengthHead_Punch = 638,
  BabyPlasma_DamageStrengthHead_Blast = 639,
  BabyPlasma_DamageStrengthHead_Heat = 640,
  BabyPlasma_DamageStrengthHead_Corrosive = 641,
  BabyPlasma_DamageStrengthHead_Electricity = 642,
  BabyPlasma_DamageStrengthHead_PsiOps = 643,
  BabyPlasma_DamageStrengthArse_PierceSoft = 644,
  BabyPlasma_DamageStrengthArse_PierceHard = 645,
  BabyPlasma_DamageStrengthArse_Slash = 646,
  BabyPlasma_DamageStrengthArse_Punch = 647,
  BabyPlasma_DamageStrengthArse_Blast = 648,
  BabyPlasma_DamageStrengthArse_Heat = 649,
  BabyPlasma_DamageStrengthArse_Corrosive = 650,
  BabyPlasma_DamageStrengthArse_Electricity = 651,
  BabyPlasma_DamageStrengthArse_PsiOps = 652,
  BabyPlasma_Damage_ThresholdForDamageToBody = 653,
  BabyPlasma_Damage_NonPlayerFactor = 654,
  BabyPlasma_AttackForceBarge_Punch = 655,
  BabyPlasma_FootImpact_PunchMultiplierFLeg = 656,
  BabyPlasma_FootImpact_PunchMultiplierMLeg = 657,
  BabyPlasma_FootImpact_PunchMultiplierRLeg = 658,
  BabyPlasma_FootImpact_DustRateModifier = 659,
  BabyPlasma_NetworkStrategy_MinTimeBeforeMove = 660,
  BabyPlasma_NetworkStrategy_MoveWaypointChance = 661,
  BabyPlasma_NetworkStrategy_WPDeltaHealth = 662,
  BabyPlasma_NetworkStrategy_DeltaHealthMoveChance = 663,
  BabyPlasma_Bolt_BlastForce = 664,
  BabyPlasma_Bolt_HotSpot = 665,
  BabyPlasma_Bolt_FallOff = 666,
  BabyPlasma_Accuracy_MinVariance = 667,
  BabyPlasma_Accuracy_MaxVariance = 668,
  BabyPlasma_Accuracy_NumberOfIntervals = 669,
  BabyPlasma_Accuracy_FirePredictionTime = 670,
  BabyPlasma_Navigator_CapsuleRadius = 671,
  BabyPlasma_Navigator_CapsuleOffsetX = 672,
  BabyPlasma_Navigator_CapsuleOffsetY = 673,
  BabyPlasma_Navigator_CapsuleOffsetZ = 674,
  BabyPlasma_Navigator_CapsuleRadiusIgnore = 675,
  BabyPlasma_Navigator_BaseSizeX = 676,
  BabyPlasma_Navigator_BaseSizeY = 677,
  BabyPlasma_Navigator_BaseSizeZ = 678,
  BabyPlasma_Navigator_MaxGradient = 679,
  BabyPlasma_Navigator_SpeedData0StepLength = 680,
  BabyPlasma_Navigator_SpeedData0StepTime = 681,
  BabyPlasma_Navigator_SpeedData0MaxTurn = 682,
  BabyPlasma_Navigator_SpeedData1StepLength = 683,
  BabyPlasma_Navigator_SpeedData1StepTime = 684,
  BabyPlasma_Navigator_SpeedData1MaxTurn = 685,
  BabyPlasma_Bolt_MinDistance = 686,
  BabyPlasma_Bolt_Speed = 687,
  Blaster_SpottingTargetBias_Player = 688,
  Blaster_SpottingTargetBias_AIHuman = 689,
  Blaster_SpottingTargetBias_Vehicle = 690,
  Blaster_SpottingIdle_RangeMax = 691,
  Blaster_SpottingIdle_RangeMin = 692,
  Blaster_SpottingIdle_Chance = 693,
  Blaster_SpottingIdle_Cone = 694,
  Blaster_SpottingAlert_RangeMax = 695,
  Blaster_SpottingAlert_RangeMin = 696,
  Blaster_SpottingAlert_Chance = 697,
  Blaster_SpottingAlert_Cone = 698,
  Blaster_Spotting_TorchSightModifier = 699,
  Blaster_DamageStrength_PierceSoft = 700,
  Blaster_DamageStrength_PierceHard = 701,
  Blaster_DamageStrength_Slash = 702,
  Blaster_DamageStrength_Punch = 703,
  Blaster_DamageStrength_Blast = 704,
  Blaster_DamageStrength_Heat = 705,
  Blaster_DamageStrength_Corrosive = 706,
  Blaster_DamageStrength_Electricity = 707,
  Blaster_DamageStrength_PsiOps = 708,
  Blaster_AttackForceBarge_Punch = 709,
  Blaster_Strategy_CloseOnTargetChance = 710,
  Blaster_Strategy_AttackRadius = 711,
  Blaster_Damage_NonPlayerFactor = 712,
  Blaster_Fire_ResistanceThreshold = 713,
  Blaster_Attack_MaxFiringRange = 714,
  Blaster_Attack_MeleeAttackDist = 715,
  Blaster_Attack_HorizontalFiringAngle = 716,
  Blaster_Attack_VerticalFiringAngle = 717,
  Blaster_Accuracy_MinimumVariance = 718,
  Blaster_Accuracy_MaximumVariance = 719,
  Blaster_Accuracy_NumberOfIntervals = 720,
  Blaster_Navigator_CapsuleRadius = 721,
  Blaster_Navigator_CapsuleOffsetX = 722,
  Blaster_Navigator_CapsuleOffsetY = 723,
  Blaster_Navigator_CapsuleOffsetZ = 724,
  Blaster_Navigator_CapsuleRadiusIgnore = 725,
  Blaster_Navigator_BaseSizeX = 726,
  Blaster_Navigator_BaseSizeY = 727,
  Blaster_Navigator_BaseSizeZ = 728,
  Blaster_Navigator_MaxGradient = 729,
  Blaster_Navigator_GridLengthMin = 730,
  Blaster_Navigator_GridLengthMax = 731,
  Blaster_Navigator_GridWidth = 732,
  Blaster_Navigator_DesiredResolutionX = 733,
  Blaster_Navigator_DesiredResolutionZ = 734,
  Blaster_Navigator_JumpHeightMin = 735,
  Blaster_Navigator_JumpHeightMax = 736,
  Blaster_Navigator_DesiredJumpResolution = 737,
  Blaster_Navigator_ExtraJumpHeightMax = 738,
  Blaster_Navigator_ExtraDesiredJumpResolution = 739,
  Blaster_Projectile_FireRate = 740,
  Blaster_Projectile_Force = 741,
  Blaster_Projectile_Hotspot = 742,
  Blaster_Projectile_Falloff = 743,
  Blaster_Misc_FacingAngle = 744,
  Plasma_SpottingTargetBias_Player = 745,
  Plasma_SpottingTargetBias_AIHuman = 746,
  Plasma_SpottingTargetBias_Vehicle = 747,
  Plasma_SpottingIdle_RangeMax = 748,
  Plasma_SpottingIdle_RangeMin = 749,
  Plasma_SpottingIdle_Chance = 750,
  Plasma_SpottingIdle_Cone = 751,
  Plasma_SpottingAlert_RangeMax = 752,
  Plasma_SpottingAlert_RangeMin = 753,
  Plasma_SpottingAlert_Chance = 754,
  Plasma_SpottingAlert_Cone = 755,
  Plasma_Spotting_TorchSightModifier = 756,
  Plasma_DamageStrengthHead_PierceSoft = 757,
  Plasma_DamageStrengthHead_PierceHard = 758,
  Plasma_DamageStrengthHead_Slash = 759,
  Plasma_DamageStrengthHead_Punch = 760,
  Plasma_DamageStrengthHead_Blast = 761,
  Plasma_DamageStrengthHead_Heat = 762,
  Plasma_DamageStrengthHead_Corrosive = 763,
  Plasma_DamageStrengthHead_Electricity = 764,
  Plasma_DamageStrengthHead_PsiOps = 765,
  Plasma_DamageStrengthArse_PierceSoft = 766,
  Plasma_DamageStrengthArse_PierceHard = 767,
  Plasma_DamageStrengthArse_Slash = 768,
  Plasma_DamageStrengthArse_Punch = 769,
  Plasma_DamageStrengthArse_Blast = 770,
  Plasma_DamageStrengthArse_Heat = 771,
  Plasma_DamageStrengthArse_Corrosive = 772,
  Plasma_DamageStrengthArse_Electricity = 773,
  Plasma_DamageStrengthArse_PsiOps = 774,
  Plasma_Damage_NonPlayerFactor = 775,
  Plasma_DamageRequiredDuringFire_Damage = 776,
  Plasma_Bolt_BlastForce = 777,
  Plasma_Bolt_BlastHotspot = 778,
  Plasma_Bolt_BlastFalloff = 779,
  Plasma_Bolt_Speed = 780,
  Plasma_FootImpact_PunchMultiplierFLeg = 781,
  Plasma_FootImpact_PunchMultiplierMLeg = 782,
  Plasma_FootImpact_PunchMultiplierRLeg = 783,
  Plasma_FootImpact_DustRateModifier = 784,
  Plasma_Spray_TargetCone = 785,
  Plasma_Spray_SprayZScale = 786,
  Plasma_Cower_HoldTime = 787,
  Hopper_SpottingTargetBias_Player = 788,
  Hopper_SpottingTargetBias_AIHuman = 789,
  Hopper_SpottingTargetBias_Vehicle = 790,
  Hopper_Strength_BulletHead = 791,
  Hopper_Strength_BulletBody = 792,
  Hopper_Strength_BulletWings = 793,
  Hopper_Strength_BulletBlast = 794,
  Hopper_Strength_Heat = 795,
  Hopper_Damage_NonPlayerFactor = 796,
  Hopper_Fire_ResistanceThreshold = 797,
  Hopper_AttackForce_InnerRadius = 798,
  Hopper_AttackForce_OuterRadius = 799,
  Hopper_AttackForce_Heat = 800,
  Hopper_AttackForce_Corrosive = 801,
  Hopper_AttackForce_Blast = 802,
  Hopper_FlightSpeed_Slow = 803,
  Hopper_FlightSpeed_Medium = 804,
  Hopper_FlightSpeed_Fast = 805,
  Hopper_FlightSpeed_VFast = 806,
  Hopper_FlightSpeed_VVFast = 807,
  Hopper_Spotting_RangeMin = 808,
  Hopper_Spotting_RangeMax = 809,
  Hopper_Spotting_Cone = 810,
  Hopper_Spotting_Chance = 811,
  Hopper_Spotting_TorchSightModifier = 812,
  Hopper_Attack_Strength = 813,
  Hopper_Audio_ScreechChance = 814,
  Hopper_Audio_ScreechGibChance = 815,
  HopperRippler_SpottingTargetBias_Player = 816,
  HopperRippler_SpottingTargetBias_AIHuman = 817,
  HopperRippler_SpottingTargetBias_Vehicle = 818,
  HopperRippler_Strength_BulletHead = 819,
  HopperRippler_Strength_BulletBody = 820,
  HopperRippler_Strength_BulletWings = 821,
  HopperRippler_Strength_Blast = 822,
  HopperRippler_Strength_Heat = 823,
  HopperRippler_Damage_NonPlayerFactor = 824,
  HopperRippler_Fire_ResistanceThreshold = 825,
  HopperRippler_FlightSpeed_Slow = 826,
  HopperRippler_FlightSpeed_Medium = 827,
  HopperRippler_FlightSpeed_Fast = 828,
  HopperRippler_FlightSpeed_VFast = 829,
  HopperRippler_FlightSpeed_VVFast = 830,
  HopperRippler_Spotting_RangeMin = 831,
  HopperRippler_Spotting_RangeMax = 832,
  HopperRippler_Spotting_Cone = 833,
  HopperRippler_Spotting_Chance = 834,
  HopperRippler_Spotting_TorchSightModifier = 835,
  HopperRippler_Attack_Strength = 836,
  HopperRippler_Attack_Speed = 837,
  HopperRippler_AttackForce_InnerRadius = 838,
  HopperRippler_AttackForce_OuterRadius = 839,
  HopperRippler_AttackForce_Blast = 840,
  HopperRippler_AttackForce_Corrosive = 841,
  HopperRippler_AttackForce_Heat = 842,
  HopperRippler_Audio_ScreechChance = 843,
  HopperRippler_Audio_ScreechGibChance = 844,
  HopperFirefly_SpottingTargetBias_Player = 845,
  HopperFirefly_SpottingTargetBias_AIHuman = 846,
  HopperFirefly_SpottingTargetBias_Vehicle = 847,
  HopperFirefly_Strength_BulletHead = 848,
  HopperFirefly_Strength_BulletBody = 849,
  HopperFirefly_Strength_BulletWings = 850,
  HopperFirefly_Strength_Blast = 851,
  HopperFirefly_Strength_Heat = 852,
  HopperFirefly_Damage_NonPlayerFactor = 853,
  HopperFirefly_Fire_ResistanceThreshold = 854,
  HopperFirefly_FlightSpeed_Slow = 855,
  HopperFirefly_FlightSpeed_Medium = 856,
  HopperFirefly_FlightSpeed_Fast = 857,
  HopperFirefly_FlightSpeed_VFast = 858,
  HopperFirefly_FlightSpeed_VVFast = 859,
  HopperFirefly_Spotting_RangeMin = 860,
  HopperFirefly_Spotting_RangeMax = 861,
  HopperFirefly_Spotting_Cone = 862,
  HopperFirefly_Spotting_Chance = 863,
  HopperFirefly_Spotting_TorchSightModifier = 864,
  HopperFirefly_Attack_Strength = 865,
  HopperFirefly_AttackForce_InnerRadius = 866,
  HopperFirefly_AttackForce_OuterRadius = 867,
  HopperFirefly_AttackForce_Heat = 868,
  HopperFirefly_AttackForce_Corrosive = 869,
  HopperFirefly_AttackForce_Blast = 870,
  HopperFirefly_Bolt_BlastForce = 871,
  HopperFirefly_Bolt_BlastHotspot = 872,
  HopperFirefly_Bolt_Falloff = 873,
  HopperFirefly_Bolt_Speed = 874,
  HopperFirefly_Audio_ScreechChance = 875,
  HopperFirefly_Audio_ScreechGibChance = 876,
  Human_Spotting_MinimumInterval = 877,
  Human_Spotting_MovingMultiplier = 878,
  Human_SpottingIdle_RangeMin = 879,
  Human_SpottingIdle_RangeMax = 880,
  Human_SpottingIdle_Chance = 881,
  Human_SpottingIdle_Cone = 882,
  Human_SpottingAlert_RangeMin = 883,
  Human_SpottingAlert_RangeMax = 884,
  Human_SpottingAlert_Chance = 885,
  Human_SpottingAlert_Cone = 886,
  Human_SpottingAlert_TargetTimeout = 887,
  Human_Grenade_MinimumInterval = 888,
  Human_Grenade_Chance = 889,
  Human_Grenade_RangeMin = 890,
  Human_Grenade_RangeMax = 891,
  Human_Grenade_LaunchVel = 892,
  Human_Grenade_ThrowDelay = 893,
  Human_Grenade_MaxAngle = 894,
  Human_Grenade_MaxRandomOffset = 895,
  Human_PsiOps_MaxKillDistance = 896,
  Human_PsiOps_AverageKillTime = 897,
  Human_PsiOps_KillGibForce = 898,
  Human_Attract_LookPlayerMinimumInterval = 899,
  Human_Attract_LookPlayerMaximumInterval = 900,
  Human_Attract_LookPlayerPersonalInterval = 901,
  Human_Attract_LookPlayerChance = 902,
  Human_Attract_NoticePlayerDistance = 903,
  Human_Attract_CelebrateChance = 904,
  Human_Attract_FireAttractMinimumInterval = 905,
  Human_Attract_FireAttractMaximumInterval = 906,
  Human_Attract_SaluteRadius = 907,
  Human_Size_SizeX = 908,
  Human_Size_SizeY = 909,
  Human_Size_SizeZ = 910,
  Human_Navigation_CapsuleRadius = 911,
  Human_Navigation_MaxGradient = 912,
  Human_Navigation_BaseSizeX = 913,
  Human_Navigation_BaseSizeY = 914,
  Human_Navigation_BaseSizeZ = 915,
  Human_Navigation_MinStaticTurnAng = 916,
  Human_Navigator_Speed0_StepLength = 917,
  Human_Navigator_Speed0_StepTime = 918,
  Human_Navigator_Speed0_MaxTurn = 919,
  Human_Navigator_Speed1_StepLength = 920,
  Human_Navigator_Speed1_StepTime = 921,
  Human_Navigator_Speed1_MaxTurn = 922,
  Human_Navigator_Speed2_StepLength = 923,
  Human_Navigator_Speed2_StepTime = 924,
  Human_Navigator_Speed2_MaxTurn = 925,
  Human_DamageStrength_StrengthBlast = 926,
  Human_DamageStrength_StrengthPierceSoft = 927,
  Human_DamageStrength_StrengthPierceHard = 928,
  Human_DamageStrength_StrengthSlash = 929,
  Human_DamageStrength_StrengthPunch = 930,
  Human_DamageStrength_StrengthHeat = 931,
  Human_DamageStrength_StrengthCorrosive = 932,
  Human_DamageStrength_StrengthElectric = 933,
  Human_DamageStrength_StrengthLight = 934,
  Human_DamageStrength_StrengthSonic = 935,
  Human_BlastLaunch_MinVal = 936,
  Human_BlastLaunch_Multiplier = 937,
  Human_BlastLaunch_TimeStep = 938,
  Human_BlastLaunch_MaxSteps = 939,
  Human_PunchLaunch_MinVal = 940,
  Human_SetOnFire_MinVal = 941,
  Human_GrenadesDropped_MinAmount = 942,
  Human_GrenadesDropped_MaxAmount = 943,
  Human_GrenadesDropped_YVelocity = 944,
  Human_GrenadesDropped_XZVelocity = 945,
  Human_Kneeling_KneelChance = 946,
  Human_Kneeling_SoundChance = 947,
  Human_Kneeling_MinTime = 948,
  Human_AttractTurn_Chance = 949,
  Human_AttractTurn_MinAngle = 950,
  Human_AttractTurn_MaxAngle = 951,
  Human_SpeechChance_KillWarrior = 952,
  Human_SpeechChance_KillTiger = 953,
  Human_SpeechChance_KillBig = 954,
  Human_SpeechChance_KillBlasterCliffmite = 955,
  Human_SpeechChance_KillSentinelCharriot = 956,
  Human_SpeechChance_KillHopper = 957,
  Human_SpeechChance_ThrowGrenade = 958,
  Human_SpeechChance_Wounded = 959,
  Human_SpeechChance_Dying = 960,
  Human_SpeechChance_HopperDuck = 961,
  Human_SpeechChance_OpenFire = 962,
  Human_SpeechChance_CeaseFire = 963,
  Human_SpeechChance_CeaseFiireDelay = 964,
  Human_SpeechChance_MaxDown = 965,
  Human_SpeechChance_ManDownRadius = 966,
  Human_SpeechChance_DropShipDisembard = 967,
  Human_SpeechChance_FriendlyFire = 968,
  Human_SpeechChance_FFMinInterval = 969,
  Human_SpeechChance_CombatCrazy = 970,
  Human_SpeechChance_CCMaxHealth = 971,
  Human_SpeechChance_CommentRange = 972,
  Human_SpeechChance_IdleComment = 973,
  Human_SpeechChance_LowHealthMinInterval = 974,
  Human_SpeechChance_LowHealthMaxInterval = 975,
  Human_SpeechChance_LowHealthPersonalInterval = 976,
  Human_SpeechChance_LowHealth = 977,
  Human_SpeechChance_LowHealthHealth = 978,
  Human_SpeechChance_MaxTimeSinceAttack = 979,
  Human_SpeechChance_MinTimeSinceHurt = 980,
  Human_SpeechChance_ManDownMinInterval = 981,
  Human_SpeechChance_ManDownMaxInterval = 982,
  Human_SpeechChance_ManDownPersonalInterval = 983,
  Human_SpeechChance_GreatShotRadius = 984,
  Human_SpeechChance_GreatShotMinInterval = 985,
  Human_SpeechChance_GreatShotPersonalInterval = 986,
  Human_SpeechChance_ThankPlayerRadius = 987,
  Human_SpeechChance_ThankPlayerMaxHealth = 988,
  Human_SpeechChance_ThankPlayerMinInterval = 989,
  Human_SpeechChance_ThankPlayerPersonalInterval = 990,
  Human_SpeechChance_BlindedMinInterval = 991,
  Human_SpeechChance_BlindedPersonalInterval = 992,
  Human_TargetBias_Warrior = 993,
  Human_TargetBias_Tiger = 994,
  Human_TargetBias_TigerShard = 995,
  Human_TargetBias_TigerSpit = 996,
  Human_TargetBias_Royal = 997,
  Human_TargetBias_RoyalX = 998,
  Human_TargetBias_Rhino = 999,
  Human_TargetBias_BabyTanker = 1000,
  Human_TargetBias_BabyPlasma = 1001,
  Human_TargetBias_Blaster = 1002,
  Human_TargetBias_Charriot = 1003,
  Human_TargetBias_Hopper = 1004,
  Human_TargetBias_FireFly = 1005,
  Human_TargetBias_Rippler = 1006,
  Human_TargetBias_Tanker = 1007,
  Human_TargetBias_Plasma = 1008,
  Human_TargetBias_CliffMite = 1009,
  Human_TargetBias_Sentinel = 1010,
  Human_Squad_Speed = 1011,
  Human_Squad_WaitDistance = 1012,
  Human_Squad_DistanceCheckInterval = 1013,
  Human_Squad_FollowMaxDist = 1014,
  Human_Squad_DropShipIgnoreTime = 1015,
  ElectricFence_PostDamageStrength_PierceSoft = 1016,
  ElectricFence_PostDamageStrength_PierceHard = 1017,
  ElectricFence_PostDamageStrength_Slash = 1018,
  ElectricFence_PostDamageStrength_Punch = 1019,
  ElectricFence_PostDamageStrength_Blast = 1020,
  ElectricFence_PostDamageStrength_Heat = 1021,
  ElectricFence_PostDamageStrength_Corrosive = 1022,
  ElectricFence_PostDamageStrength_Electricity = 1023,
  ElectricFence_PostDamageStrength_PsiOps = 1024,
  ElectricFence_FenceParameters_ElectricityForce = 1025,
  ElectricFence_FenceParameters_HeightBottom = 1026,
  ElectricFence_FenceParameters_HeightTop = 1027,
  ElectricFence_FenceParameters_TestDelay = 1028,
  Player_Movement_RunSpeed = 1029,
  Player_Movement_DuckSpeed = 1030,
  Player_Movement_MoveLag = 1031,
  Player_Movement_TurnSpeed = 1032,
  Player_Movement_TurnLag = 1033,
  Player_Movement_MaxGradient = 1034,
  Player_Movement_SlideGradient = 1035,
  Player_Movement_MaxSlideSpeed = 1036,
  Player_Movement_StepHeight = 1037,
  Player_Movement_StepLenght = 1038,
  Player_Movement_SphereRadius = 1039,
  Player_Movement_HeightStand = 1040,
  Player_Movement_HeightDuck = 1041,
  Player_Movement_EyeHeight = 1042,
  Player_Movement_JumpVelUp = 1043,
  Player_Movement_DuckRate = 1044,
  Player_Health_RegenerateRate0 = 1045,
  Player_Health_RegenerateRate1 = 1046,
  Player_Shake_ShakeAmplitude = 1047,
  Player_Shake_ShakeDuration = 1048,
  Player_Crouch_CrouchAccuracy = 1049,
  Player_Crouch_CrouchBlastDamageReduction = 1050,
  Player_AmmoCapacity_Bullet = 1051,
  Player_AmmoCapacity_Grenade = 1052,
  Player_AmmoCapacity_Shotgun = 1053,
  Player_AmmoCapacity_Rocket = 1054,
  Player_AmmoCapacity_Missile = 1055,
  Player_AmmoCapacity_Slug = 1056,
  Player_AmmoCapacity_HandGrenade = 1057,
  Player_Strength_BulletSoft = 1058,
  Player_Strength_Bullet = 1059,
  Player_Strength_Slash = 1060,
  Player_Strength_Punch = 1061,
  Player_Strength_Blast = 1062,
  Player_Strength_Heat = 1063,
  Player_Strength_Corrosive = 1064,
  Player_Strength_Electricity = 1065,
  Player_Strength_PsiOps = 1066,
  Player_Strength_Light = 1067,
  Player_Strength_Sonic = 1068,
  Player_Shield_BulletSoft = 1069,
  Player_Shield_Bullet = 1070,
  Player_Shield_Slash = 1071,
  Player_Shield_Punch = 1072,
  Player_Shield_Blast = 1073,
  Player_Shield_Heat = 1074,
  Player_Shield_Corrosive = 1075,
  Player_Shield_Electricity = 1076,
  Player_Shield_PsiOps = 1077,
  Player_Shield_Light = 1078,
  Player_Shield_Sonic = 1079,
  Player_Shield_RechargeDelay = 1080,
  Player_Shield_RechargeRate = 1081,
  Player_Misc_HealthPickup = 1082,
  Player_Misc_CriticalHealth = 1083,
  Player_HitShake_Length = 1084,
  Player_HitShake_AngleX = 1085,
  Player_HitShake_AngleY = 1086,
  Player_HitShake_AngleZ = 1087,
  Player_Fall_HurtSpeed = 1088,
  Player_Fall_DamageMultiplier = 1089,
  Player_Fall_MinHeight = 1090,
  Player_Fall_MaxHeight = 1091,
  Player_Fall_KillPlaneHeight = 1092,
  Player_Fire_CheckInterval = 1093,
  Player_Misc_FireDamage = 1094,
  MoritaMk4_General_ClicksBeforeReload = 1095,
  MoritaMK4_General_ClicksBeforeReload = 1095,
  MoritaMK4_Bullets_MaxNumber = 1096,
  MoritaMK4_Ammo_LowAmmo = 1097,
  MoritaMK4_Grenades_MaxNumber = 1098,
  MoritaMK4_Bullets_MinBurst = 1099,
  MoritaMK4_Bullets_FireRate = 1100,
  MoritaMK4_Bullets_MinReloadTime = 1101,
  MoritaMK4_Bullets_MaxReloadTime = 1102,
  MoritaMK4_Bullets_Range = 1103,
  MoritaMK4_Bullets_Spread = 1104,
  MoritaMK4_Bullets_SpreadFirst = 1105,
  MoritaMK4_Bullets_Strength = 1106,
  MoritaMK4_Grenade_LaunchVel = 1107,
  MoritaMK4_Grenade_LaunchVelZ = 1108,
  MoritaMK4_FireShake_Time = 1109,
  MoritaMK4_FireShake_AngleX = 1110,
  MoritaMK4_FireShake_AngleY = 1111,
  MoritaMK4_FireShake_AngleZ = 1112,
  MoritaMK4_GrenadeJolt_Time = 1113,
  MoritaMK4_GrenadeJolt_AngleX = 1114,
  MoritaMK4_Grenade_Drag = 1115,
  MoritaMK4_Grenade_Blastforce = 1116,
  MoritaMK4_Grenade_BlastHotspot = 1117,
  MoritaMK4_Grenade_BlastFalloff = 1118,
  MoritaMK4_Grenade_ProximityCheckTime = 1119,
  MoritaMK4_Grenade_ProximityCheckRadius = 1120,
  MoritaMK4_Grenade_ProximityCheckLife = 1121,
  MoritaMK4_AIDrop_MinGrenades = 1122,
  MoritaMK4_AIDrop_MaxGrenades = 1123,
  MoritaShotgun_Ammo_MaxNumber = 1124,
  MoritaShotgun_Ammo_LowAmmo = 1125,
  MoritaShotgun_Primary_BurstNumber = 1126,
  MoritaShotgun_Primary_BurstPause = 1127,
  MoritaShotgun_Primary_FireRate = 1128,
  MoritaShotgun_Primary_Range = 1129,
  MoritaShotgun_Primary_Spread = 1130,
  MoritaShotgun_Primary_SpreadFirst = 1131,
  MoritaShotgun_Primary_Strength = 1132,
  MoritaShotgun_Secondary_NumBullets = 1133,
  MoritaShotgun_Secondary_Range = 1134,
  MoritaShotgun_Secondary_Spread = 1135,
  MoritaShotgun_Secondary_Strength = 1136,
  MoritaShotgun_Fire1Shake_Time = 1137,
  MoritaShotgun_Fire1Shake_AngleX = 1138,
  MoritaShotgun_Fire1Shake_AngleY = 1139,
  MoritaShotgun_Fire1Shake_AngleZ = 1140,
  MoritaShotgun_Fire2Jolt_Time = 1141,
  MoritaShotgun_Fire2Jolt_AngleX = 1142,
  MoritaShotgun_AIDrop_MinBullets = 1143,
  MoritaShotgun_AIDrop_MaxBullets = 1144,
  MoritaGrenade_Ammo_MaxNumber = 1145,
  MoritaGrenade_Ammo_LowAmmo = 1146,
  MoritaGrenade_Ammo_NumGrenades = 1147,
  MoritaGrenade_Primary_BurstNumber = 1148,
  MoritaGrenade_Primary_BurstPause = 1149,
  MoritaGrenade_Primary_FireRate = 1150,
  MoritaGrenade_Primary_Range = 1151,
  MoritaGrenade_Primary_Spread = 1152,
  MoritaGrenade_Primary_SpreadFirst = 1153,
  MoritaGrenade_Primary_Strength = 1154,
  MoritaGrenade_Grenade_LaunchVelY = 1155,
  MoritaGrenade_Grenade_LaunchVelZ = 1156,
  MoritaGrenade_FireShake_Time = 1157,
  MoritaGrenade_FireShake_AngleX = 1158,
  MoritaGrenade_FireShake_AngleY = 1159,
  MoritaGrenade_FireShake_AngleZ = 1160,
  MoritaGrenade_GrenadeJolt_Time = 1161,
  MoritaGrenade_GrenadeJolt_AngleX = 1162,
  MoritaGrenade_AIDrop_MinBullets = 1163,
  MoritaGrenade_AIDrop_MaxBullets = 1164,
  MoritaGrenade_AIDrop_MinGrenades = 1165,
  MoritaGrenade_AIDrop_MaxGrenades = 1166,
  MoritaZoom_Ammo_MaxNumber = 1167,
  MoritaZoom_Ammo_LowAmmo = 1168,
  MoritaZoom_Primary_BurstNumber = 1169,
  MoritaZoom_Primary_BurstPause = 1170,
  MoritaZoom_Primary_FireRate = 1171,
  MoritaZoom_Primary_Range = 1172,
  MoritaZoom_Primary_Spread = 1173,
  MoritaZoom_Primary_SpreadFirst = 1174,
  MoritaZoom_Primary_Strength = 1175,
  MoritaZoom_Secondary_BurstNumber = 1176,
  MoritaZoom_Secondary_BurstPause = 1177,
  MoritaZoom_Secondary_FireRate = 1178,
  MoritaZoom_Secondary_Range = 1179,
  MoritaZoom_Secondary_Spread = 1180,
  MoritaZoom_Secondary_SpreadFirst = 1181,
  MoritaZoom_Secondary_Strength = 1182,
  MoritaZoom_Secondary_ZoomFactor = 1183,
  MoritaZoom_Fire1Shake_Time = 1184,
  MoritaZoom_Fire1Shake_AngleX = 1185,
  MoritaZoom_Fire1Shake_AngleY = 1186,
  MoritaZoom_Fire1Shake_AngleZ = 1187,
  MoritaZoom_Fire2Shake_Time = 1188,
  MoritaZoom_Fire2Shake_AngleX = 1189,
  MoritaZoom_Fire2Shake_AngleY = 1190,
  MoritaZoom_Fire2Shake_AngleZ = 1191,
  MoritaZoom_AIDrop_MinBullets = 1192,
  MoritaZoom_AIDrop_MaxBullets = 1193,
  MoritaCarbine_Ammo_MaxNumber = 1194,
  MoritaCarbine_Ammo_LowAmmo = 1195,
  MoritaCarbine_Primary_BurstNumber = 1196,
  MoritaCarbine_Primary_BurstPause = 1197,
  MoritaCarbine_Primary_FireRate = 1198,
  MoritaCarbine_Primary_Range = 1199,
  MoritaCarbine_Primary_Spread = 1200,
  MoritaCarbine_Primary_SpreadFirst = 1201,
  MoritaCarbine_Primary_Strength = 1202,
  MoritaCarbine_FireShake_Time = 1203,
  MoritaCarbine_FireShake_AngleX = 1204,
  MoritaCarbine_FireShake_AngleY = 1205,
  MoritaCarbine_FireShake_AngleZ = 1206,
  MoritaCarbine_Secondary_BurstNumber = 1207,
  MoritaCarbine_Secondary_BurstPause = 1208,
  MoritaCarbine_Secondary_FireRate = 1209,
  MoritaCarbine_Secondary_Range = 1210,
  MoritaCarbine_Secondary_Spread = 1211,
  MoritaCarbine_Secondary_SpreadFirst = 1212,
  MoritaCarbine_Secondary_Strength = 1213,
  MoritaCarbine_FireShake2_Time = 1214,
  MoritaCarbine_FireShake2_AngleX = 1215,
  MoritaCarbine_FireShake2_AngleY = 1216,
  MoritaCarbine_FireShake2_AngleZ = 1217,
  MoritaCarbine_AIDrop_MinBullets = 1218,
  MoritaCarbine_AIDrop_MaxBullets = 1219,
  Shotgun_Ammo_MaxShells = 1220,
  Shotgun_Ammo_LowAmmo = 1221,
  Shotgun_Primary_NumberShells = 1222,
  Shotgun_Primary_NumberRayTests = 1223,
  Shotgun_Primary_RayTestRange = 1224,
  Shotgun_Primary_RayTestSpread = 1225,
  Shotgun_Primary_RayTestStrength = 1226,
  Shotgun_Primary_BlastRange = 1227,
  Shotgun_Primary_BlastAngle = 1228,
  Shotgun_Primary_BlastStrength = 1229,
  Shotgun_PrimaryJolt_Time = 1230,
  Shotgun_PrimaryJolt_Angle = 1231,
  Shotgun_Secondary_NumberShells = 1232,
  Shotgun_Secondary_NumberRayTests = 1233,
  Shotgun_Secondary_RayTestRange = 1234,
  Shotgun_Secondary_RayTestSpread = 1235,
  Shotgun_Secondary_RayTestStrength = 1236,
  Shotgun_Secondary_BlastRange = 1237,
  Shotgun_Secondary_BlastAngle = 1238,
  Shotgun_Secondary_BlastStrength = 1239,
  Shotgun_SecondaryJolt_Time = 1240,
  Shotgun_SecondaryJolt_Angle = 1241,
  Shotgun_AIDrop_MinShells = 1242,
  Shotgun_AIDrop_MaxShells = 1243,
  Railgun_Ammo_MaxNumber = 1244,
  Railgun_Ammo_LowAmmo = 1245,
  Railgun_Bullet_Range = 1246,
  Railgun_Bullet_Spread = 1247,
  Railgun_Bullet_Strength = 1248,
  Railgun_Shockwave_Strength = 1249,
  Railgun_Shockwave_HotSpot = 1250,
  Railgun_Shockwave_Falloff = 1251,
  Railgun_Shockwave_Spacing = 1252,
  Railgun_Shockwave_TimeDelay = 1253,
  Railgun_ZoomFactor_Stage1 = 1254,
  Railgun_ZoomFactor_Stage2 = 1255,
  Railgun_JoltUnZoomed_Time = 1256,
  Railgun_JoltUnZoomed_AngleX = 1257,
  Railgun_JoltZoom1_Time = 1258,
  Railgun_JoltZoom1_AngleX = 1259,
  Railgun_JoltZoom2_Time = 1260,
  Railgun_JoltZoom2_AngleX = 1261,
  RocketLauncher_Ammo_MaxRockets = 1264,
  RocketLauncher_Ammo_LowAmmo = 1265,
  RocketLauncher_Firing_SpeedupNum = 1266,
  RocketLauncher_Firing_DelayMax = 1267,
  RocketLauncher_Firing_DelayMin = 1268,
  RocketLauncher_Firing_JoltTime = 1269,
  RocketLauncher_Firing_JoltAngle = 1270,
  RocketLauncher_LockOn_MaxNumber = 1271,
  RocketLauncher_LockOn_MaxRange = 1272,
  RocketLauncher_LockOn_MaxAngleX = 1273,
  RocketLauncher_LockOn_MaxAngleY = 1274,
  RocketLauncher_LockOn_ShowAngleX = 1275,
  RocketLauncher_LockOn_ShowAngleY = 1276,
  RocketLauncher_LockOn_JoltTime = 1277,
  RocketLauncher_LockOn_JoltAngle = 1278,
  RocketLauncher_AIDrop_MinRockets = 1279,
  RocketLauncher_AIDrop_MaxRockets = 1280,
  RocketLauncher_Rocket_NOLOCKSpeed = 1281,
  RocketLauncher_Rocket_NOLOCKLifeTime = 1282,
  RocketLauncher_Rocket_LOCKEDSpeed = 1283,
  RocketLauncher_Rocket_LOCKEDLifeTime = 1284,
  RocketLauncher_Rocket_TurnRate = 1285,
  RocketLauncher_Rocket_WeaveAngle = 1286,
  RocketLauncher_Rocket_WeaveFrequency = 1287,
  RocketLauncher_Blast_StrengthBlast = 1288,
  RocketLauncher_Blast_StrengthHeat = 1289,
  RocketLauncher_Blast_HotspotRadius = 1290,
  RocketLauncher_Blast_FalloffRadius = 1291,
  MissileLauncher_Ammo_MaxMissiles = 1292,
  MissileLauncher_Zoom_ZoomFactor = 1293,
  MissileLauncher_Shake_Fire1JoltTime = 1294,
  MissileLauncher_Shake_Fire1JoltAngle = 1295,
  MissileLauncher_Shake_Fire2JoltTime = 1296,
  MissileLauncher_Shake_Fire2JoltAngle = 1297,
  MissileLauncher_MissileLaunch_LaunchSpeed = 1298,
  MissileLauncher_MissileLaunch_LaunchingTime = 1299,
  MissileLauncher_MissileLaunch_PitchingAngle = 1300,
  MissileLauncher_MissileFlight_FlightSpeed = 1301,
  MissileLauncher_MissileFlight_LifeTime = 1302,
  MissileLauncher_MissileFlight_Guidance = 1303,
  MissileLauncher_MissileFlight_TurnRate = 1304,
  MissileLauncher_MissileBlast_ForceDamage = 1305,
  MissileLauncher_MissileBlast_HeatDamage = 1306,
  MissileLauncher_MissileBlast_Hotspot = 1307,
  MissileLauncher_MissileBlast_Falloff = 1308,
  MissileLauncher_CoreDamage_CoreRadius = 1309,
  MissileLauncher_CoreDamage_PierceSoft = 1310,
  MissileLauncher_CoreDamage_PierceHard = 1311,
  MissileLauncher_CoreDamage_Slash = 1312,
  MissileLauncher_CoreDamage_Punch = 1313,
  MissileLauncher_CoreDamage_Blast = 1314,
  MissileLauncher_CoreDamage_Heat = 1315,
  MissileLauncher_CoreDamage_Corrosive = 1316,
  MissileLauncher_CoreDamage_Electricity = 1317,
  MissileLauncher_CoreDamage_PsiOps = 1318,
  MissileLauncher_CoreDamage_Light = 1319,
  MissileLauncher_CoreDamage_Sonic = 1320,
  HandGrenade_FirstPerson_CountdownTime = 1321,
  HandGrenade_FirstPerson_StayPrimedTime = 1322,
  HandGrenade_FirstPerson_LaunchVelUp = 1323,
  HandGrenade_FirstPerson_LaunchVelForce = 1324,
  HandGrenade_MovementData_Radius = 1325,
  HandGrenade_MovementData_BounceNormalLoss = 1326,
  HandGrenade_MovementData_BounceParallelVel = 1327,
  HandGrenade_MovementData_RollingDrag = 1328,
  HandGrenade_MovementData_ActiveTime = 1329,
  HandGrenade_MovementData_TrooperCheckDelay = 1330,
  HandGrenade_Blast_Force = 1331,
  HandGrenade_Blast_HotSpot = 1332,
  HandGrenade_Blast_FallOff = 1333,
  HandGrenade_SafeRadius_Player = 1334,
  HandGrenade_SafeRadius_AIHuman = 1335,
  StaticGunDouble_General_BulletStrength = 1336,
  StaticGunDouble_General_FireRate = 1337,
  StaticGunDouble_Rotation_RateHeading = 1338,
  StaticGunDouble_Rotation_RatePitch = 1339,
  StaticGunDouble_Rotation_GunLag = 1340,
  StaticGunDouble_Temerature_FiringDelta = 1341,
  StaticGunDouble_Temerature_CoolingRate = 1342,
  StaticGunDouble_Temerature_OverheatTime = 1343,
  StaticGunDouble_General_ZoomFactor = 1344,
  StaticGunDouble_General_ZoomRate = 1345,
  StaticGunDouble_FireShake_Time = 1346,
  StaticGunDouble_FireShake_AngleX = 1347,
  StaticGunDouble_FireShake_AngleY = 1348,
  StaticGunDouble_FireShake_AngleZ = 1349,
  StaticGunDouble_AIParameters_ReTargetTime = 1350,
  StaticGunDouble_AIParameters_RateHeading = 1351,
  StaticGunDouble_AIParameters_RatePitch = 1352,
  NukeLauncher_Missile_FlightSpeed = 1353,
  NukeLauncher_Missile_ClimbFactor = 1354,
  AmmoPickup_AmmoBox_CheckRadius = 1355,
  AmmoPickup_AmmoBox_CheckTime = 1356,
  AmmoPickup_AmmoBox_PickupNumber = 1357,
  AmmoPickup_AmmoBox_TimePerPickup = 1358,
  AmmoPickup_AmmoBundle_CheckRadius = 1359,
  AmmoPickup_AmmoBundle_CheckTime = 1360,
  FlyingVehicles_GruntDropship_FlightSpeedSlow = 1361,
  FlyingVehicles_GruntDropship_FlightSpeedMedium = 1362,
  FlyingVehicles_GruntDropship_FlightSpeedFast = 1363,
  FlyingVehicles_GruntDropship_RotationRate = 1364,
  FlyingVehicles_MarauderDropship_FlightSpeedSlow = 1365,
  FlyingVehicles_MarauderDropship_FlightSpeedMedium = 1366,
  FlyingVehicles_MarauderDropship_FlightSpeedFast = 1367,
  FlyingVehicles_MarauderDropship_RotationRate = 1368,
  FlyingVehicles_MarauderDropship_PlayerPosX = 1369,
  FlyingVehicles_MarauderDropship_PlayerPosY = 1370,
  FlyingVehicles_MarauderDropship_PlayerPosZ = 1371,
  FlyingVehicles_MarauderDropship_PlayerHeading = 1372,
  FlyingVehicles_MarauderDropship_PlayerHeadingArc = 1373,
  FlyingVehicles_MarauderDropship_PlayerPitch = 1374,
  FlyingVehicles_MarauderDropship_PlayerPitchArc = 1375,
  FlyingVehicles_CargoDropship_FlightSpeedSlow = 1376,
  FlyingVehicles_CargoDropship_FlightSpeedMedium = 1377,
  FlyingVehicles_CargoDropship_FlightSpeedFast = 1378,
  FlyingVehicles_CargoDropship_RotationRate = 1379,
  FlyingVehicles_Bomber_FlightSpeedSlow = 1380,
  FlyingVehicles_Bomber_FlightSpeedMedium = 1381,
  FlyingVehicles_Bomber_FlightSpeedFast = 1382,
  FlyingVehicles_Bomber_RotationRate = 1383,
  FlyingVehicles_BomberBomb_NapalmLaunchNum = 1384,
  FlyingVehicles_BomberBomb_NaplamLaunchTime = 1385,
  FlyingVehicles_BomberBomb_NaplamLaunchSize = 1386,
  FlyingVehicles_BomberBomb_NaplamBlastForce = 1387,
  FlyingVehicles_BomberBomb_NaplamBlastHotspot = 1388,
  FlyingVehicles_BomberBomb_NaplamBlastFalloff = 1389,
  FlyingVehicles_BomberBomb_BlastForce = 1390,
  FlyingVehicles_BomberBomb_BlastHotspot = 1391,
  FlyingVehicles_BomberBomb_BlastFalloff = 1392,
  FlyingVehicles_BomberBomb_ProjectileLaunchSpeed = 1393,
  FlyingVehicles_DownDraft_RayLength = 1394,
  LandMine_Warning_Radius = 1395,
  LandMine_Instant_Radius = 1396,
  LandMine_Warning_Time = 1397,
  LandMine_Blast_Force = 1398,
  LandMine_Blast_Hotspot = 1399,
  LandMine_Blast_Falloff = 1400,
  AIManager_MaxDeadBodies = 1401,
  AIManager_DeadBodyRangeFactor = 1402,
  AIManager_DeadBodyAngleFactor = 1403,
  AIManager_DeadBodyAgeFactor = 1404,
  AIManager_DeadBodyOnFireFactor = 1405,
  AIManager_MaxNumberRagdolls = 1406,
  AIManager_BodyFadeOutTime = 1407,
  AIManager_BigBodyBodyFadeOutTime = 1408,
  AIManager_WarriorRumbleVolumeFactor = 1409,
  AIManager_WarriorRumbleMaxDist = 1410,
  AIManager_WarriorRumbleCutoffDist = 1411,
  RagDoll_DragFactor = 1412,
  RagDoll_BlastFactor = 1413,
};

struct TDSValue {
  int field_0;
  int field_4;
  int field_8;
  float value;
};

struct TDSValueGroup {
  TDSValue *values[1414];
};

struct TDSSettings {
  float GetValue(TDSValueIndex index);

  static TDSSettings *Get();

  std::string globalEasySuffix;
  std::string globalNormalSuffix;
  std::string globalHardSuffix;
  std::string globalVeryHardSuffix;
  std::string levelSuffix;
  TDSValueGroup easyDifficulty;
  TDSValueGroup normalDifficulty;
  TDSValueGroup hardDifficulty;
  TDSValueGroup veryHardDifficulty;
  TDSValueGroup level;
  int field_6F04;
  int field_6F08;
  int field_6F0C;
  int field_6F10;
  int field_6F14;
  int field_6F18;
  int field_6F1C;
  int field_6F20;
  int field_6F24;
  int field_6F28;
  int field_6F2C;
  int field_6F30;
  int field_6F34;
  int field_6F38;
  int field_6F3C;
  int field_6F40;
  int field_6F44;
  int field_6F48;
  int field_6F4C;
  int field_6F50;
  int field_6F54;
  int field_6F58;
  int field_6F5C;
  int field_6F60;
  int field_6F64;
  int field_6F68;
  int field_6F6C;
  int field_6F70;
  int field_6F74;
  int field_6F78;
  int field_6F7C;
  int field_6F80;
  int field_6F84;
  int field_6F88;
  int field_6F8C;
  int field_6F90;
  int field_6F94;
  int field_6F98;
  int field_6F9C;
  int field_6FA0;
  int field_6FA4;
  int field_6FA8;
  int field_6FAC;
  int field_6FB0;
  int field_6FB4;
  int field_6FB8;
  int field_6FBC;
  int field_6FC0;
  int field_6FC4;
  int field_6FC8;
  int field_6FCC;
  int field_6FD0;
  int field_6FD4;
  int field_6FD8;
  int field_6FDC;
  int field_6FE0;
  int field_6FE4;
  int field_6FE8;
  int field_6FEC;
  int field_6FF0;
  int field_6FF4;
  int field_6FF8;
  int field_6FFC;
  int field_7000;
  int field_7004;
  int field_7008;
  int field_700C;
  int field_7010;
  int field_7014;
  int field_7018;
  int field_701C;
  int field_7020;
  int field_7024;
  int field_7028;
  int field_702C;
  int field_7030;
  int field_7034;
  int field_7038;
  int field_703C;
  int field_7040;
  int field_7044;
  int field_7048;
  int field_704C;
  int field_7050;
  int field_7054;
  int field_7058;
  int field_705C;
  int field_7060;
  int field_7064;
  int field_7068;
  int field_706C;
  int field_7070;
  int field_7074;
  int field_7078;
  int field_707C;
  int field_7080;
  int field_7084;
  int field_7088;
  int field_708C;
  int field_7090;
  int field_7094;
  int field_7098;
  int field_709C;
  int field_70A0;
  int field_70A4;
  int field_70A8;
  int field_70AC;
  int field_70B0;
  int field_70B4;
  int field_70B8;
  int field_70BC;
  int field_70C0;
  int field_70C4;
  int field_70C8;
  int field_70CC;
  int field_70D0;
  int field_70D4;
  int field_70D8;
  int field_70DC;
  int field_70E0;
  int field_70E4;
  int field_70E8;
  int field_70EC;
  int field_70F0;
  int field_70F4;
  int field_70F8;
  int field_70FC;
  int field_7100;
  int field_7104;
  int field_7108;
  int field_710C;
  int field_7110;
  int field_7114;
  int field_7118;
  int field_711C;
  int field_7120;
  int field_7124;
  int field_7128;
  int field_712C;
  int field_7130;
  int field_7134;
  int field_7138;
  int field_713C;
  int field_7140;
  int field_7144;
  int field_7148;
  int field_714C;
  int field_7150;
  int field_7154;
  int field_7158;
  int field_715C;
  int field_7160;
  int field_7164;
  int field_7168;
  int field_716C;
  int field_7170;
  int field_7174;
  int field_7178;
  int field_717C;
  int field_7180;
  int field_7184;
  int field_7188;
  int field_718C;
  int field_7190;
  int field_7194;
  int field_7198;
  int field_719C;
  int field_71A0;
  int field_71A4;
  int field_71A8;
  int field_71AC;
  int field_71B0;
  int field_71B4;
  int field_71B8;
  int field_71BC;
  int field_71C0;
  int field_71C4;
  int field_71C8;
  int field_71CC;
  int field_71D0;
  int field_71D4;
  int field_71D8;
  int field_71DC;
  int field_71E0;
  int field_71E4;
  int field_71E8;
  int field_71EC;
  int field_71F0;
  int field_71F4;
  int field_71F8;
  int field_71FC;
  int field_7200;
  int field_7204;
  int field_7208;
  int field_720C;
  int field_7210;
  int field_7214;
  int field_7218;
  int field_721C;
  int field_7220;
};
